# -*- mode: python ; coding: utf-8 -*-
block_cipher = None

a = Analysis(
    ['main_simple.py'],
    pathex=[],
    binaries=[],
    # Kullanıcıya ait kimlik bilgilerini uygulama paketine eklemeyin.
    datas=[],
    hiddenimports=[
        'PyQt5',
        'PyQt5.QtCore',
        'PyQt5.QtGui',
        'PyQt5.QtWidgets',
        'PyQt5.QtWebEngineWidgets',
        'PyQt5.QtWebEngineCore',
        'ee',
        'ee.batch',
        'ee.cli',
        'folium',
        'folium.plugins',
        'branca',
        'branca.element',
        'jinja2',
        'jinja2.ext',
        'requests',
        'google',
        'google.auth',
        'google.oauth2',
        'google.auth.transport',
        'google.auth.transport.requests',
        'httplib2',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='MeyveAgaclariAnalizi',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
